"""Default Chart of Accounts seed data for Ghanaian schools
This provides a standard CoA template that schools can use as a starting point.
Accounts follow Ghana's standard numbering system (1000s=Assets, 2000s=Liabilities, etc.)
"""

DEFAULT_CHART_OF_ACCOUNTS = [
    # ==================== ASSETS (1000-1999) ====================
    {
        "account_code": "1010",
        "account_name": "Business Checking Account",
        "account_type": "asset",
        "account_category": "bank_accounts",
        "description": "Primary operating bank account",
        "normal_balance": "debit",
        "system_role": "default_cash_account",
    },
    {
        "account_code": "1020",
        "account_name": "Business Savings Account",
        "account_type": "asset",
        "account_category": "bank_accounts",
        "description": "Reserve/emergency fund bank account",
        "normal_balance": "debit",
    },
    {
        "account_code": "1030",
        "account_name": "Petty Cash",
        "account_type": "asset",
        "account_category": "bank_accounts",
        "description": "Small cash disbursements",
        "normal_balance": "debit",
    },
    {
        "account_code": "1040",
        "account_name": "Paystack Clearing Account",
        "account_type": "asset",
        "account_category": "bank_accounts",
        "description": "Online (Paystack) payments land here at collection time — before the school's own MoMo/bank withdrawal actually clears. Cleared to 1010 when a settlement withdrawal completes.",
        "normal_balance": "debit",
        "system_role": "paystack_clearing_account",
    },
    {
        "account_code": "1100",
        "account_name": "Accounts Receivable - Student Fees",
        "account_type": "asset",
        "account_category": "accounts_receivable",
        "description": "Outstanding student fee payments",
        "normal_balance": "debit",
        "system_role": "student_fees_receivable",
    },
    {
        "account_code": "1110",
        "account_name": "Allowance for Doubtful Accounts",
        "account_type": "asset",
        "account_category": "accounts_receivable",
        "description": "Reserve for uncollectible fees",
        "normal_balance": "credit",
    },
    {
        "account_code": "1200",
        "account_name": "Prepaid Expenses",
        "account_type": "asset",
        "account_category": "prepaid_expenses",
        "description": "Paid but not yet incurred expenses (insurance, subscriptions)",
        "normal_balance": "debit",
    },
    {
        "account_code": "1210",
        "account_name": "Staff Loans Receivable",
        "account_type": "asset",
        "account_category": "accounts_receivable",
        "description": "Outstanding staff loans and salary advances, repaid via payroll deduction",
        "normal_balance": "debit",
        "system_role": "staff_loan_receivable",
    },
    {
        "account_code": "1300",
        "account_name": "Fixed Assets - Building",
        "account_type": "asset",
        "account_category": "fixed_assets",
        "description": "School building and structures",
        "normal_balance": "debit",
    },
    {
        "account_code": "1310",
        "account_name": "Fixed Assets - Furniture & Equipment",
        "account_type": "asset",
        "account_category": "fixed_assets",
        "description": "Desks, chairs, computers, lab equipment",
        "normal_balance": "debit",
    },
    {
        "account_code": "1320",
        "account_name": "Fixed Assets - Vehicles",
        "account_type": "asset",
        "account_category": "fixed_assets",
        "description": "School vehicles and transport",
        "normal_balance": "debit",
    },
    {
        "account_code": "1330",
        "account_name": "Accumulated Depreciation - Building",
        "account_type": "asset",
        "account_category": "fixed_assets",
        "description": "Depreciation reserve for building",
        "normal_balance": "credit",
    },
    {
        "account_code": "1340",
        "account_name": "Accumulated Depreciation - Equipment",
        "account_type": "asset",
        "account_category": "fixed_assets",
        "description": "Depreciation reserve for furniture and equipment",
        "normal_balance": "credit",
    },
    
    # ==================== LIABILITIES (2000-2999) ====================
    {
        "account_code": "2100",
        "account_name": "Salaries Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "Staff salaries accrued but not yet paid",
        "normal_balance": "credit",
        "system_role": "salaries_payable",
    },
    {
        "account_code": "2110",
        "account_name": "NSSF Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "National Social Security Fund contribution due",
        "normal_balance": "credit",
        "system_role": "nssf_payable",
    },
    {
        "account_code": "2120",
        "account_name": "Pension Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "Pension contributions due",
        "normal_balance": "credit",
        "system_role": "pension_payable",
    },
    {
        "account_code": "2130",
        "account_name": "Income Tax Withheld Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "Income tax withheld from employee salaries",
        "normal_balance": "credit",
        "system_role": "income_tax_payable",
    },
    {
        "account_code": "2112",
        "account_name": "Employer SSNIT Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "Employer-side SSNIT Tier-1 contribution owed (statutory ~8% of basic, on top of the employee's own deducted share) — previously computed only as an on-the-fly export estimate, never tracked as a real liability.",
        "normal_balance": "credit",
        "system_role": "employer_ssnit_payable",
    },
    {
        "account_code": "2113",
        "account_name": "SSNIT Tier 2 Payable",
        "account_type": "liability",
        "account_category": "salaries_payable",
        "description": "Mandatory Tier-2 occupational pension (5% of basic, employer-funded) owed to a licensed private pension trustee, separate from SSNIT Tier-1 itself.",
        "normal_balance": "credit",
        "system_role": "ssnit_tier2_payable",
    },
    {
        "account_code": "2150",
        "account_name": "Refunds Payable",
        "account_type": "liability",
        "account_category": "accounts_payable",
        "description": "Money already received (e.g. a fee overpayment) that is owed back to a parent — recognized as a liability the moment it's flagged, not left unrecorded until the refund actually happens.",
        "normal_balance": "credit",
        "system_role": "refunds_payable",
    },
    {
        "account_code": "2200",
        "account_name": "Accounts Payable - Vendors",
        "account_type": "liability",
        "account_category": "accounts_payable",
        "description": "Outstanding invoices to suppliers",
        "normal_balance": "credit",
        "system_role": "accounts_payable_vendors",
    },
    {
        "account_code": "2300",
        "account_name": "Short-Term Debt",
        "account_type": "liability",
        "account_category": "short_term_debt",
        "description": "Loans due within 12 months",
        "normal_balance": "credit",
    },
    {
        "account_code": "2400",
        "account_name": "Long-Term Debt",
        "account_type": "liability",
        "account_category": "long_term_debt",
        "description": "Loans due beyond 12 months",
        "normal_balance": "credit",
    },
    
    # ==================== EQUITY (3000-3999) ====================
    {
        "account_code": "3100",
        "account_name": "Accumulated Surplus",
        "account_type": "equity",
        "account_category": "accumulated_surplus",
        "description": "Cumulative surplus from all years of operation",
        "normal_balance": "credit",
        "system_role": "retained_earnings",
    },
    {
        "account_code": "3110",
        "account_name": "Current Year Surplus",
        "account_type": "equity",
        "account_category": "accumulated_surplus",
        "description": "Surplus/deficit for the current fiscal year",
        "normal_balance": "credit",
    },
    
    # ==================== REVENUE (4000-4999) ====================
    {
        "account_code": "4100",
        "account_name": "Student Tuition Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Main tuition revenue from students",
        "normal_balance": "credit",
    },
    {
        "account_code": "4110",
        "account_name": "Examination Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Fees for examinations and testing",
        "normal_balance": "credit",
    },
    {
        "account_code": "4120",
        "account_name": "Sports Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Physical education and sports program fees",
        "normal_balance": "credit",
    },
    {
        "account_code": "4130",
        "account_name": "ICT Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Computer and IT resource fees",
        "normal_balance": "credit",
    },
    {
        "account_code": "4140",
        "account_name": "Library Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Library access and resource fees",
        "normal_balance": "credit",
    },
    {
        "account_code": "4150",
        "account_name": "PTA Levy",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "Parent-Teacher Association contributions",
        "normal_balance": "credit",
    },
    {
        "account_code": "4160",
        "account_name": "Maintenance Fees",
        "account_type": "revenue",
        "account_category": "student_fees",
        "description": "School facilities maintenance fees",
        "normal_balance": "credit",
    },
    {
        "account_code": "4200",
        "account_name": "Donations",
        "account_type": "revenue",
        "account_category": "donations",
        "description": "Monetary gifts from individuals and organizations",
        "normal_balance": "credit",
    },
    {
        "account_code": "4300",
        "account_name": "Government Grants",
        "account_type": "revenue",
        "account_category": "grants",
        "description": "Funding from government education programs",
        "normal_balance": "credit",
    },
    {
        "account_code": "4400",
        "account_name": "Interest Income",
        "account_type": "revenue",
        "account_category": "other_income",
        "description": "Interest earned on bank accounts",
        "normal_balance": "credit",
    },
    {
        "account_code": "4500",
        "account_name": "Other Revenue",
        "account_type": "revenue",
        "account_category": "other_income",
        "description": "Miscellaneous income sources",
        "normal_balance": "credit",
    },
    
    # ==================== EXPENSES (5000-5999) ====================
    {
        "account_code": "5100",
        "account_name": "Salaries and Wages",
        "account_type": "expense",
        "account_category": "salaries_wages",
        "description": "Staff compensation and wages",
        "normal_balance": "debit",
        "system_role": "salaries_expense",
    },
    {
        "account_code": "5110",
        "account_name": "Payroll Taxes and Contributions",
        "account_type": "expense",
        "account_category": "salaries_wages",
        "description": "Employer-side statutory contributions (SSNIT Tier-1 + Tier-2) — the school's own cost, on top of what's deducted from staff pay.",
        "normal_balance": "debit",
        "system_role": "employer_statutory_contributions_expense",
    },
    {
        "account_code": "5200",
        "account_name": "Utilities - Electricity",
        "account_type": "expense",
        "account_category": "utilities",
        "description": "Electricity costs",
        "normal_balance": "debit",
    },
    {
        "account_code": "5210",
        "account_name": "Utilities - Water",
        "account_type": "expense",
        "account_category": "utilities",
        "description": "Water supply costs",
        "normal_balance": "debit",
    },
    {
        "account_code": "5220",
        "account_name": "Internet and Telephone",
        "account_type": "expense",
        "account_category": "utilities",
        "description": "Communication service expenses",
        "normal_balance": "debit",
    },
    {
        "account_code": "5300",
        "account_name": "Office Supplies",
        "account_type": "expense",
        "account_category": "supplies",
        "description": "Stationery, paper, and office materials",
        "normal_balance": "debit",
    },
    {
        "account_code": "5310",
        "account_name": "Classroom Supplies",
        "account_type": "expense",
        "account_category": "supplies",
        "description": "Teaching materials and instructional supplies",
        "normal_balance": "debit",
    },
    {
        "account_code": "5320",
        "account_name": "Laboratory Supplies",
        "account_type": "expense",
        "account_category": "supplies",
        "description": "Science lab materials and chemicals",
        "normal_balance": "debit",
    },
    {
        "account_code": "5400",
        "account_name": "Repairs and Maintenance",
        "account_type": "expense",
        "account_category": "repairs_maintenance",
        "description": "Building and equipment repairs",
        "normal_balance": "debit",
    },
    {
        "account_code": "5500",
        "account_name": "Transport Costs",
        "account_type": "expense",
        "account_category": "transport_costs",
        "description": "Vehicle fuel, repairs, and maintenance",
        "normal_balance": "debit",
    },
    {
        "account_code": "5600",
        "account_name": "Professional Services",
        "account_type": "expense",
        "account_category": "contracted_services",
        "description": "Consulting, legal, accounting services",
        "normal_balance": "debit",
    },
    {
        "account_code": "5610",
        "account_name": "Contracted Cleaning Services",
        "account_type": "expense",
        "account_category": "contracted_services",
        "description": "School cleaning and sanitation",
        "normal_balance": "debit",
    },
    {
        "account_code": "5620",
        "account_name": "Security Services",
        "account_type": "expense",
        "account_category": "contracted_services",
        "description": "Security personnel and equipment",
        "normal_balance": "debit",
    },
    {
        "account_code": "5700",
        "account_name": "Depreciation Expense",
        "account_type": "expense",
        "account_category": "depreciation",
        "description": "Periodic depreciation of fixed assets",
        "normal_balance": "debit",
    },
    {
        "account_code": "5800",
        "account_name": "Insurance",
        "account_type": "expense",
        "account_category": "other_expenses",
        "description": "School insurance premiums",
        "normal_balance": "debit",
    },
    {
        "account_code": "5850",
        "account_name": "Bank & Payment Processing Fees",
        "account_type": "expense",
        "account_category": "other_expenses",
        "description": "Paystack/bank transaction and transfer fees",
        "normal_balance": "debit",
        "system_role": "payment_processing_fees",
    },
    {
        "account_code": "5900",
        "account_name": "Other Expenses",
        "account_type": "expense",
        "account_category": "other_expenses",
        "description": "Miscellaneous operating expenses",
        "normal_balance": "debit",
    },
    {
        "account_code": "5910",
        "account_name": "Bad Debt Expense",
        "account_type": "expense",
        "account_category": "other_expenses",
        "description": "Student fee balances formally written off as uncollectable",
        "normal_balance": "debit",
        "system_role": "bad_debt_expense",
    },
]
