"""Staff router"""
import os
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status, Query, UploadFile, File
from sqlmodel import select, func, SQLModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timedelta
from typing import Optional
import re
import secrets
from models.staff import Staff, StaffCreate, StaffType, StaffStatus, TeacherAssignment, TeacherAssignmentUpdate, PayoutVerificationStatus
from models.classroom import Class, Subject
from models.school import School
from models.user import User, UserRole
from models.otp import OTPSettings, OTP
from models.payroll import PayrollContract
from database import get_session
from auth import get_current_user, require_roles, get_password_hash, encrypt_onboarding_password, decrypt_onboarding_password
from dependencies import resolve_campus_scope, resolve_write_campus_id, assert_campus_access
from services.csv_import_service import CSVImportService
from services.paystack_service import PaystackService

router = APIRouter(prefix="/staff", tags=["Staff"])
ADMIN_ROLES = (UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)
STAFF_PORTAL_ROLES = tuple(role for role in UserRole if role not in {
    UserRole.SUPER_ADMIN,
    UserRole.STUDENT,
    UserRole.PARENT,
})


async def _validate_manager_id(session: AsyncSession, school_id: str, manager_id: Optional[str], staff_id: Optional[str] = None) -> None:
    """manager_id was previously accepted and stored with zero validation —
    not checked for same-school membership, not checked against
    manager_id == staff_id (self-management), and not checked for a cycle
    up the chain. A self-referencing manager_id directly enables the
    self-approval bypass fixed in routers/leave_requests.py::
    approve_leave_request (manager_approve_leave_request trusts
    requester.manager_id == manager_staff.id at face value), and a cycle
    would corrupt get_org_chart with an infinite loop. staff_id is the
    record being created/updated — None for create_staff, since a not-yet-
    inserted row can't be its own manager or appear in a cycle anyway."""
    if not manager_id:
        return
    if staff_id and manager_id == staff_id:
        raise HTTPException(status_code=422, detail="A staff member cannot be their own manager")

    result = await session.execute(select(Staff).where(Staff.id == manager_id, Staff.school_id == school_id))
    manager = result.scalar_one_or_none()
    if not manager:
        raise HTTPException(status_code=404, detail="manager_id does not exist for this school")

    if staff_id:
        # Walk up the chain from the proposed manager; if it ever reaches
        # staff_id, assigning this manager would create a cycle. Bounded
        # hop count as a defensive backstop against a pre-existing cycle
        # this check didn't catch before it existed.
        seen = set()
        current = manager
        for _ in range(50):
            if current.id == staff_id:
                raise HTTPException(status_code=422, detail="This manager assignment would create a management cycle")
            if not current.manager_id or current.id in seen:
                break
            seen.add(current.id)
            next_result = await session.execute(select(Staff).where(Staff.id == current.manager_id, Staff.school_id == school_id))
            current = next_result.scalar_one_or_none()
            if not current:
                break


async def _get_own_staff_record(current_user: User, session: AsyncSession) -> Staff:
    result = await session.execute(select(Staff).where(Staff.user_id == current_user.id))
    staff = result.scalar_one_or_none()
    if not staff and current_user.school_id:
        result = await session.execute(
            select(Staff).where(Staff.email == current_user.email, Staff.school_id == current_user.school_id)
        )
        staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff profile not found. Please ensure your portal credentials have been generated by the admin.")
    return staff


def _serialize_payout_details(staff: Staff) -> dict:
    return {
        "payout_account_type": staff.payout_account_type,
        "payout_bank_code": staff.payout_bank_code,
        "payout_account_number": staff.payout_account_number,
        "payout_account_name": staff.payout_account_name,
        "payout_verification_status": staff.payout_verification_status.value if hasattr(staff.payout_verification_status, "value") else str(staff.payout_verification_status),
        "payout_submitted_at": staff.payout_submitted_at.isoformat() if staff.payout_submitted_at else None,
        "payout_verified_at": staff.payout_verified_at.isoformat() if staff.payout_verified_at else None,
        "payout_rejection_reason": staff.payout_rejection_reason,
        "has_subaccount": bool(staff.paystack_subaccount_code),
    }


async def ensure_single_class_teacher(
    session: AsyncSession,
    class_id: str,
    academic_term_id: str,
    exclude_assignment_id: Optional[str] = None,
) -> None:
    """A class should have at most one 'class teacher' per term — that flag is used
    elsewhere (report cards, attendance responsibility) as if it identifies a single
    person. Reject a second one instead of silently allowing two."""
    query = select(TeacherAssignment).where(
        TeacherAssignment.class_id == class_id,
        TeacherAssignment.academic_term_id == academic_term_id,
        TeacherAssignment.is_class_teacher == True,
    )
    if exclude_assignment_id:
        query = query.where(TeacherAssignment.id != exclude_assignment_id)
    result = await session.execute(query)
    # .first() rather than scalar_one_or_none() — existing data can already have
    # more than one class teacher for a class/term (the exact gap this guards
    # against), so a strict one-or-none read would itself raise.
    if result.scalars().first():
        raise HTTPException(
            status_code=400,
            detail="This class already has a class teacher for this term — remove that assignment's class-teacher flag first"
        )


class AssignTeacherRequest(SQLModel):
    class_id: str
    subject_id: str
    academic_term_id: str
    is_class_teacher: bool = False



def _normalize_name(name: str) -> str:
    """Normalize name for email generation"""
    cleaned = name.strip().lower()
    cleaned = re.sub(r'[^a-z0-9]+', '', cleaned)
    return cleaned


async def _delete_user_with_otp_cleanup(user_id: str, session: AsyncSession):
    """Delete a user and its related OTP records to avoid foreign key violations"""
    # Delete OTP settings for this user
    otp_settings_result = await session.execute(
        select(OTPSettings).where(OTPSettings.user_id == user_id)
    )
    otp_settings = otp_settings_result.scalars().all()
    for otp_setting in otp_settings:
        await session.delete(otp_setting)
    
    # Delete OTP codes for this user
    otp_result = await session.execute(
        select(OTP).where(OTP.user_id == user_id)
    )
    otp_codes = otp_result.scalars().all()
    for otp_code in otp_codes:
        await session.delete(otp_code)
    
    # Delete the user
    user_result = await session.execute(select(User).where(User.id == user_id))
    user = user_result.scalar_one_or_none()
    if user:
        await session.delete(user)


async def _get_school_short_code(school_id: str, session: AsyncSession) -> str:
    """Get school short code for email domain"""
    if not school_id:
        return 'school'
    result = await session.execute(select(School).where(School.id == school_id))
    school = result.scalar_one_or_none()
    if not school or not getattr(school, 'code', None):
        return 'school'
    return str(school.code).strip().lower()


async def _create_portal_user(
    first_name: str,
    last_name: str,
    school_id: str,
    role: UserRole,
    session: AsyncSession
):
    """Create a portal user with generated email and password"""
    school_short = await _get_school_short_code(school_id, session)
    base_local_part = f"{_normalize_name(first_name)}.{_normalize_name(last_name)}"

    email = f"{base_local_part}@{school_short}.school.edu.gh"
    suffix = 1

    while True:
        user_exists = await session.execute(select(User).where(User.email == email))
        if not user_exists.scalar_one_or_none():
            break
        email = f"{base_local_part}{suffix}@{school_short}.school.edu.gh"
        suffix += 1

    password = secrets.token_urlsafe(10)
    user = User(
        email=email,
        password_hash=get_password_hash(password),
        plain_text_password=encrypt_onboarding_password(password),
        first_name=first_name,
        last_name=last_name,
        role=role,
        school_id=school_id,
        is_active=True,
        must_change_password=True
    )

    try:
        session.add(user)
        await session.flush()
    except IntegrityError:
        await session.rollback()
        result = await session.execute(select(User).where(User.email == email))
        existing_user = result.scalar_one_or_none()
        if existing_user:
            return existing_user, decrypt_onboarding_password(existing_user.plain_text_password) or "N/A"
        raise
    
    return user, password


@router.post("", response_model=dict)
async def create_staff(
    staff_data: StaffCreate,
    background_tasks: BackgroundTasks,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Create a new staff member"""
    school_id = current_user.school_id
    if not school_id and current_user.role != UserRole.SUPER_ADMIN:
        raise HTTPException(status_code=400, detail="No school context")

    staff_data.campus_id = resolve_write_campus_id(current_user, staff_data.campus_id)

    if not staff_data.staff_id:
        staff_data.staff_id = f"STF-{datetime.now().year}-{secrets.token_hex(3).upper()}"

    result = await session.execute(
        select(Staff).where(
            Staff.school_id == school_id,
            Staff.staff_id == staff_data.staff_id
        )
    )
    if result.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="Staff ID already exists")

    await _validate_manager_id(session, school_id, staff_data.manager_id)

    staff = Staff(school_id=school_id, **staff_data.model_dump())
    session.add(staff)
    await session.commit()
    await session.refresh(staff)

    from services.webhook_service import emit_event
    await emit_event(
        session, background_tasks, school_id, "staff.created",
        {
            "id": staff.id,
            "staff_id": staff.staff_id,
            "first_name": staff.first_name,
            "last_name": staff.last_name,
            "position": staff.position,
        },
    )

    return {
        "id": staff.id,
        "school_id": staff.school_id,
        "staff_id": staff.staff_id,
        "first_name": staff.first_name,
        "last_name": staff.last_name,
        "email": staff.email,
        "staff_type": staff.staff_type,
        "position": staff.position,
        "status": staff.status,
        "created_at": staff.created_at.isoformat()
    }


@router.post("/import", response_model=dict)
async def import_staff_csv(
    file: UploadFile = File(...),
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Import staff from CSV file"""
    if not file.filename.endswith('.csv'):
        raise HTTPException(status_code=400, detail="File must be a CSV file")
    
    school_id = current_user.school_id
    if not school_id:
        raise HTTPException(status_code=400, detail="No school context")
    
    # Read file content
    content = await file.read()
    
    # Import staff
    import_service = CSVImportService(session, school_id, current_user)
    result = await import_service.import_staff(content)
    
    if not result['success'] and result['success_count'] == 0:
        raise HTTPException(status_code=400, detail=result['message'])
    
    return result


@router.get("/me/profile", response_model=dict)
async def get_my_staff_profile(current_user: User = Depends(get_current_user), session: AsyncSession = Depends(get_session)):
    """Best-effort lookup of the caller's own Staff record — returns
    staff_id: null rather than 404 when there's no linked profile (e.g. a
    super_admin with no teaching/HR role), so a frontend feature gated on
    'am I staff, and do I manage anyone' can check this without try/catch."""
    result = await session.execute(select(Staff).where(Staff.user_id == current_user.id))
    staff = result.scalar_one_or_none()
    if not staff and current_user.school_id:
        result = await session.execute(
            select(Staff).where(Staff.email == current_user.email, Staff.school_id == current_user.school_id)
        )
        staff = result.scalar_one_or_none()
    if not staff:
        return {"staff_id": None}

    reports_result = await session.execute(select(func.count(Staff.id)).where(Staff.manager_id == staff.id))
    return {
        "staff_id": staff.id,
        "first_name": staff.first_name,
        "last_name": staff.last_name,
        "manager_id": staff.manager_id,
        "direct_report_count": reports_result.scalar() or 0,
    }


@router.get("", response_model=dict)
async def list_staff(
    staff_type: Optional[StaffType] = None,
    campus_id: Optional[str] = None,
    status: Optional[StaffStatus] = None,
    search: Optional[str] = None,
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """List staff with pagination"""
    school_id = current_user.school_id
    if not school_id and current_user.role != UserRole.SUPER_ADMIN:
        raise HTTPException(status_code=403, detail="No school context")
    
    query = select(Staff)
    count_query = select(func.count(Staff.id))
    
    if school_id:
        query = query.where(Staff.school_id == school_id)
        count_query = count_query.where(Staff.school_id == school_id)
    
    if staff_type:
        query = query.where(Staff.staff_type == staff_type)
        count_query = count_query.where(Staff.staff_type == staff_type)

    campus_id = resolve_campus_scope(current_user, campus_id)
    if campus_id:
        query = query.where(Staff.campus_id == campus_id)
        count_query = count_query.where(Staff.campus_id == campus_id)

    if status:
        query = query.where(Staff.status == status)
        count_query = count_query.where(Staff.status == status)
    
    if search:
        search_filter = (
            Staff.first_name.ilike(f"%{search}%") |
            Staff.last_name.ilike(f"%{search}%") |
            Staff.staff_id.ilike(f"%{search}%")
        )
        query = query.where(search_filter)
        count_query = count_query.where(search_filter)
    
    total_result = await session.execute(count_query)
    total = total_result.scalar()
    
    offset = (page - 1) * limit
    query = query.offset(offset).limit(limit).order_by(Staff.first_name)
    
    result = await session.execute(query)
    staff_list = result.scalars().all()
    
    # Build response with payroll contract info
    staff_items = []
    for s in staff_list:
        # Fetch active payroll contract for this staff
        contract_result = await session.execute(
            select(PayrollContract).where(
                PayrollContract.staff_id == s.id,
                PayrollContract.school_id == s.school_id,
                PayrollContract.is_active == True
            ).order_by(PayrollContract.effective_from.desc()).limit(1)
        )
        contract = contract_result.scalar_one_or_none()
        
        staff_item = {
            "id": s.id,
            "school_id": s.school_id,
            "staff_id": s.staff_id,
            "first_name": s.first_name,
            "last_name": s.last_name,
            "full_name": f"{s.first_name} {s.last_name}",
            "email": s.email,
            "phone": s.phone,
            "staff_type": s.staff_type,
            "position": s.position,
            "department": s.department,
            "status": s.status,
            "role": s.role.value if s.role else UserRole.TEACHER.value,
            "photo_url": s.photo_url,
            "campus_id": s.campus_id,
            "manager_id": s.manager_id,
            # Portal account link, if any — needed by routers/roles.py's
            # assign-role-to-user flow to target the right User row.
            "user_id": s.user_id,
            "payroll_contract": {
                "basic_salary": float(contract.basic_salary),
                "tax_rate_percent": float(contract.tax_rate_percent),
                "pension_rate_percent": float(contract.pension_rate_percent)
            } if contract else None
        }
        staff_items.append(staff_item)
    
    return {
        "items": staff_items,
        "total": total,
        "page": page,
        "limit": limit,
        "pages": (total + limit - 1) // limit
    }


@router.get("/teachers", response_model=list[dict])
async def list_teachers(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """List all teaching staff"""
    school_id = current_user.school_id
    if not school_id:
        raise HTTPException(status_code=403, detail="No school context")
    
    result = await session.execute(
        select(Staff).where(
            Staff.school_id == school_id,
            Staff.staff_type == StaffType.TEACHING,
            Staff.status == StaffStatus.ACTIVE
        ).order_by(Staff.first_name)
    )
    teachers = result.scalars().all()
    
    return [
        {
            "id": t.id,
            "staff_id": t.staff_id,
            "first_name": t.first_name,
            "last_name": t.last_name,
            "full_name": f"{t.first_name} {t.last_name}",
            "email": t.email,
            "department": t.department,
            "qualification": t.qualification
        }
        for t in teachers
    ]


@router.get("/my-classes", response_model=dict)
async def get_teacher_classes(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """Get classes assigned to the current logged-in teacher"""
    # Find the staff record for this user
    # First try by user_id, then fallback to email matching
    result = await session.execute(select(Staff).where(Staff.user_id == current_user.id))
    staff = result.scalar_one_or_none()
    
    # Fallback: try to match by email and school
    if not staff and current_user.school_id:
        result = await session.execute(
            select(Staff).where(
                Staff.email == current_user.email,
                Staff.school_id == current_user.school_id
            )
        )
        staff = result.scalar_one_or_none()
    
    if not staff:
        raise HTTPException(
            status_code=404, 
            detail="Staff profile not found. Please ensure your portal credentials have been generated by the admin."
        )
    
    if staff.staff_type != StaffType.TEACHING:
        raise HTTPException(status_code=403, detail="Not a teaching staff member")
    
    # Get all assignments for this teacher
    assignments_result = await session.execute(
        select(TeacherAssignment).where(TeacherAssignment.staff_id == staff.id)
    )
    assignments = assignments_result.scalars().all()
    
    classes_data = []
    for assignment in assignments:
        class_result = await session.execute(select(Class).where(Class.id == assignment.class_id))
        cls = class_result.scalar_one_or_none()
        
        subject_result = await session.execute(select(Subject).where(Subject.id == assignment.subject_id))
        subject = subject_result.scalar_one_or_none()
        
        if cls:
            classes_data.append({
                "assignment_id": assignment.id,
                "class_id": cls.id,
                "class_name": cls.name,
                "class_level": cls.level,
                "subject_id": assignment.subject_id,
                "subject_name": subject.name if subject else "Unknown",
                "subject_code": subject.code if subject else "N/A",
                "is_class_teacher": assignment.is_class_teacher,
                "academic_term_id": assignment.academic_term_id
            })
    
    return {
        "items": classes_data,
        "total": len(classes_data)
    }


# ── Payout settlement details ───────────────────────────────────────────────
# Where money for staff-initiated paid activities (currently: extra classes)
# is sent. Staff submits their own bank/MoMo details; an admin verifies once,
# which creates a real Paystack subaccount — after that, payments route
# straight to the staff member with no manual payout step on the school's
# side at all.

@router.get("/my-payout-details", response_model=dict)
async def get_my_payout_details(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_own_staff_record(current_user, session)
    return _serialize_payout_details(staff)


@router.put("/my-payout-details", response_model=dict)
async def submit_my_payout_details(
    payload: dict,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    account_type = payload.get("account_type")
    bank_code = payload.get("bank_code")
    account_number = payload.get("account_number")
    if account_type not in ("bank", "mobile_money") or not bank_code or not account_number:
        raise HTTPException(status_code=400, detail="account_type (bank/mobile_money), bank_code, and account_number are required")

    staff = await _get_own_staff_record(current_user, session)

    paystack_secret_key = os.getenv("PAYSTACK_SECRET_KEY", "")
    if not paystack_secret_key:
        raise HTTPException(status_code=503, detail="Payment gateway not configured")

    # This is the actual anti-fraud check — Paystack confirms who really
    # owns this account before we ever store it or show it to an admin to
    # "verify". A typo'd or made-up number fails here, not after.
    paystack = PaystackService(paystack_secret_key)
    resolved = await paystack.resolve_account_number(account_number=account_number, bank_code=bank_code)
    if not resolved.get("success"):
        raise HTTPException(status_code=400, detail=resolved.get("error", "Could not verify this account number"))

    staff.payout_account_type = account_type
    staff.payout_bank_code = bank_code
    staff.payout_account_number = account_number
    staff.payout_account_name = resolved["account_name"]
    staff.payout_verification_status = PayoutVerificationStatus.PENDING
    staff.payout_submitted_at = datetime.utcnow()
    staff.payout_rejection_reason = None
    staff.paystack_subaccount_code = None  # re-submitting invalidates any prior subaccount
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()
    await session.refresh(staff)
    return _serialize_payout_details(staff)


@router.get("/payout-details/pending", response_model=dict)
async def list_pending_payout_details(
    current_user: User = Depends(require_roles(*ADMIN_ROLES)),
    session: AsyncSession = Depends(get_session),
):
    result = await session.execute(
        select(Staff).where(
            Staff.school_id == current_user.school_id,
            Staff.payout_verification_status == PayoutVerificationStatus.PENDING,
        )
    )
    staff_list = result.scalars().all()
    return {
        "staff": [
            {"id": s.id, "name": f"{s.first_name} {s.last_name}", "position": s.position, **_serialize_payout_details(s)}
            for s in staff_list
        ]
    }


@router.get("/{staff_id}/payout-details", response_model=dict)
async def get_staff_payout_details(
    staff_id: str,
    current_user: User = Depends(require_roles(*ADMIN_ROLES)),
    session: AsyncSession = Depends(get_session),
):
    result = await session.execute(select(Staff).where(Staff.id == staff_id, Staff.school_id == current_user.school_id))
    staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    return _serialize_payout_details(staff)


@router.post("/{staff_id}/payout-details/verify", response_model=dict)
async def verify_staff_payout_details(
    staff_id: str,
    current_user: User = Depends(require_roles(*ADMIN_ROLES)),
    session: AsyncSession = Depends(get_session),
):
    result = await session.execute(select(Staff).where(Staff.id == staff_id, Staff.school_id == current_user.school_id))
    staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    if staff.payout_verification_status != PayoutVerificationStatus.PENDING:
        raise HTTPException(status_code=400, detail=f"Nothing to verify — status is {staff.payout_verification_status}")

    paystack_secret_key = os.getenv("PAYSTACK_SECRET_KEY", "")
    if not paystack_secret_key:
        raise HTTPException(status_code=503, detail="Payment gateway not configured")

    paystack = PaystackService(paystack_secret_key)
    result_sub = await paystack.create_subaccount(
        business_name=f"{staff.first_name} {staff.last_name}",
        settlement_bank=staff.payout_bank_code,
        account_number=staff.payout_account_number,
        percentage_charge=0,  # school takes no cut — the staff member gets the full amount
    )
    if not result_sub.get("success"):
        raise HTTPException(status_code=502, detail=result_sub.get("error", "Failed to create Paystack subaccount"))

    staff.paystack_subaccount_code = result_sub["subaccount_code"]
    staff.payout_verification_status = PayoutVerificationStatus.VERIFIED
    staff.payout_verified_at = datetime.utcnow()
    staff.payout_verified_by = current_user.id
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()
    await session.refresh(staff)
    return _serialize_payout_details(staff)


@router.post("/{staff_id}/payout-details/reject", response_model=dict)
async def reject_staff_payout_details(
    staff_id: str,
    payload: dict,
    current_user: User = Depends(require_roles(*ADMIN_ROLES)),
    session: AsyncSession = Depends(get_session),
):
    result = await session.execute(select(Staff).where(Staff.id == staff_id, Staff.school_id == current_user.school_id))
    staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    if staff.payout_verification_status != PayoutVerificationStatus.PENDING:
        raise HTTPException(status_code=400, detail=f"Nothing to reject — status is {staff.payout_verification_status}")

    staff.payout_verification_status = PayoutVerificationStatus.REJECTED
    staff.payout_rejection_reason = payload.get("reason")
    staff.payout_verified_by = current_user.id
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()
    await session.refresh(staff)
    return _serialize_payout_details(staff)


@router.get("/banks/list", response_model=dict)
async def list_payout_banks(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    paystack_secret_key = os.getenv("PAYSTACK_SECRET_KEY", "")
    if not paystack_secret_key:
        raise HTTPException(status_code=503, detail="Payment gateway not configured")
    paystack = PaystackService(paystack_secret_key)
    result = await paystack.list_banks()
    if not result.get("success"):
        raise HTTPException(status_code=502, detail=result.get("error", "Failed to load bank list"))
    return {"banks": result["banks"]}


@router.get("/{staff_id}", response_model=dict)
async def get_staff(
    staff_id: str,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """Get staff details"""
    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    
    if current_user.role != UserRole.SUPER_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")
    assert_campus_access(current_user, staff.campus_id)

    assignments = []
    if staff.staff_type == StaffType.TEACHING:
        assign_result = await session.execute(
            select(TeacherAssignment).where(TeacherAssignment.staff_id == staff.id)
        )
        for a in assign_result.scalars().all():
            class_result = await session.execute(select(Class).where(Class.id == a.class_id))
            cls = class_result.scalar_one_or_none()
            
            subject_result = await session.execute(select(Subject).where(Subject.id == a.subject_id))
            subject = subject_result.scalar_one_or_none()
            
            assignments.append({
                "id": a.id,
                "class_id": a.class_id,
                "class_name": cls.name if cls else "Unknown",
                "subject_id": a.subject_id,
                "subject_name": subject.name if subject else "Unknown",
                "is_class_teacher": a.is_class_teacher
            })
    
    # Portal login credentials are only shown to admins managing accounts, or
    # to the staff member viewing their own record — not to every same-school
    # user this endpoint is otherwise open to (e.g. a TEACHER looking up a
    # colleague), who would otherwise walk away with that colleague's
    # plaintext password.
    portal_account = None
    if staff.user_id:
        can_see_credentials = (
            current_user.role in (UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)
            or current_user.id == staff.user_id
        )
        if can_see_credentials:
            user_result = await session.execute(select(User).where(User.id == staff.user_id))
            user = user_result.scalar_one_or_none()
            if user:
                portal_account = {
                    "email": user.email,
                    "password": decrypt_onboarding_password(user.plain_text_password)
                }

    manager_name = None
    if staff.manager_id:
        manager_result = await session.execute(select(Staff).where(Staff.id == staff.manager_id))
        manager = manager_result.scalar_one_or_none()
        if manager:
            manager_name = f"{manager.first_name} {manager.last_name}"

    return {
        "id": staff.id,
        "school_id": staff.school_id,
        "staff_id": staff.staff_id,
        "first_name": staff.first_name,
        "last_name": staff.last_name,
        "full_name": f"{staff.first_name} {staff.last_name}",
        "email": staff.email,
        "phone": staff.phone,
        "date_of_birth": staff.date_of_birth,
        "gender": staff.gender,
        "staff_type": staff.staff_type,
        "position": staff.position,
        "department": staff.department,
        "manager_id": staff.manager_id,
        "manager_name": manager_name,
        "qualification": staff.qualification,
        "date_joined": staff.date_joined,
        "status": staff.status,
        "role": staff.role.value if staff.role else UserRole.TEACHER.value,
        "photo_url": staff.photo_url,
        "portal_account": portal_account,
        "assignments": assignments,
        "probation_status": staff.probation_status,
        "probation_end_date": staff.probation_end_date,
        "probation_confirmed_at": staff.probation_confirmed_at.isoformat() if staff.probation_confirmed_at else None,
        "probation_confirmed_by": staff.probation_confirmed_by,
        "created_at": staff.created_at.isoformat()
    }


@router.put("/{staff_id}", response_model=dict)
async def update_staff(
    staff_id: str,
    staff_data: StaffCreate,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Update staff details"""
    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    
    if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")
    assert_campus_access(current_user, staff.campus_id)
    staff_data.campus_id = resolve_write_campus_id(current_user, staff_data.campus_id)
    await _validate_manager_id(session, staff.school_id, staff_data.manager_id, staff_id=staff.id)

    for key, value in staff_data.model_dump().items():
        setattr(staff, key, value)
    
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()

    return {"message": "Staff updated successfully"}


# ==================== Probation ====================
PROBATION_STATUSES = {"not_applicable", "on_probation", "confirmed", "extended", "terminated"}


class StaffProbationStart(SQLModel):
    probation_end_date: str  # "YYYY-MM-DD"


class StaffProbationDecision(SQLModel):
    decision: str  # "confirmed" | "extended" | "terminated"
    new_probation_end_date: Optional[str] = None  # required when decision == "extended"
    notes: Optional[str] = None


@router.put("/{staff_id}/probation/start", response_model=dict)
async def start_probation(
    staff_id: str,
    body: StaffProbationStart,
    current_user: User = Depends(require_roles(*ADMIN_ROLES, UserRole.HR)),
    session: AsyncSession = Depends(get_session)
):
    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    if current_user.role != UserRole.SUPER_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")

    staff.probation_status = "on_probation"
    staff.probation_end_date = body.probation_end_date
    staff.probation_confirmed_at = None
    staff.probation_confirmed_by = None
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()
    return {"message": "Probation started", "probation_end_date": staff.probation_end_date}


@router.put("/{staff_id}/probation/decide", response_model=dict)
async def decide_probation(
    staff_id: str,
    body: StaffProbationDecision,
    current_user: User = Depends(require_roles(*ADMIN_ROLES, UserRole.HR)),
    session: AsyncSession = Depends(get_session)
):
    """Confirm, extend, or terminate a staff member's probation. Extending
    requires a new end date; confirming/terminating doesn't need one."""
    if body.decision not in {"confirmed", "extended", "terminated"}:
        raise HTTPException(status_code=400, detail="decision must be confirmed, extended, or terminated")
    if body.decision == "extended" and not body.new_probation_end_date:
        raise HTTPException(status_code=400, detail="new_probation_end_date is required when extending probation")

    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    if current_user.role != UserRole.SUPER_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")
    if staff.probation_status != "on_probation":
        raise HTTPException(status_code=400, detail="This staff member is not currently on probation")

    staff.probation_status = body.decision
    if body.decision == "extended":
        staff.probation_end_date = body.new_probation_end_date
    staff.probation_confirmed_at = datetime.utcnow()
    staff.probation_confirmed_by = current_user.id
    staff.updated_at = datetime.utcnow()
    session.add(staff)
    await session.commit()
    return {"message": f"Probation {body.decision}", "probation_status": staff.probation_status, "probation_end_date": staff.probation_end_date}


@router.get("/probation/upcoming", response_model=list[dict])
async def list_upcoming_probation_reviews(
    days: int = Query(30, ge=1, le=180),
    current_user: User = Depends(require_roles(*ADMIN_ROLES, UserRole.HR)),
    session: AsyncSession = Depends(get_session)
):
    """Staff currently on probation whose end date falls within the next
    `days` days — or has already passed with no decision recorded yet."""
    school_id = current_user.school_id
    if not school_id:
        raise HTTPException(status_code=400, detail="No school context")

    cutoff = (datetime.utcnow() + timedelta(days=days)).strftime("%Y-%m-%d")
    result = await session.execute(
        select(Staff).where(
            Staff.school_id == school_id,
            Staff.probation_status == "on_probation",
            Staff.probation_end_date.is_not(None),
            Staff.probation_end_date <= cutoff,
        ).order_by(Staff.probation_end_date)
    )
    today = datetime.utcnow().strftime("%Y-%m-%d")
    return [
        {
            "staff_id": s.id, "name": f"{s.first_name} {s.last_name}", "position": s.position,
            "department": s.department, "probation_end_date": s.probation_end_date,
            "is_overdue": s.probation_end_date < today,
        }
        for s in result.scalars().all()
    ]


@router.get("/employment/upcoming-expiry", response_model=list[dict])
async def list_upcoming_employment_expiry(
    days: int = Query(30, ge=1, le=180),
    current_user: User = Depends(require_roles(*ADMIN_ROLES, UserRole.HR)),
    session: AsyncSession = Depends(get_session)
):
    """Any staff member with a contract_end_date within the next `days`
    days (or already passed with nothing recorded) — independent of
    PayrollContract's own expiry reminder (routers/payroll.py's
    list_expiring_contracts), which only ever sees staff who actually have
    a payroll contract row. An NSS posting, paid a government allowance
    rather than a school salary, previously had zero expiry tracking at
    all because of that gap."""
    school_id = current_user.school_id
    if not school_id:
        raise HTTPException(status_code=400, detail="No school context")

    cutoff = (datetime.utcnow() + timedelta(days=days)).strftime("%Y-%m-%d")
    result = await session.execute(
        select(Staff).where(
            Staff.school_id == school_id,
            Staff.status == StaffStatus.ACTIVE,
            Staff.contract_end_date.is_not(None),
            Staff.contract_end_date <= cutoff,
        ).order_by(Staff.contract_end_date)
    )
    today = datetime.utcnow().strftime("%Y-%m-%d")
    return [
        {
            "staff_id": s.id, "name": f"{s.first_name} {s.last_name}", "position": s.position,
            "department": s.department, "employment_type": s.employment_type,
            "contract_end_date": s.contract_end_date, "is_overdue": s.contract_end_date < today,
        }
        for s in result.scalars().all()
    ]


@router.post("/{staff_id}/assignments", response_model=dict)
async def assign_teacher(
    staff_id: str,
    body: AssignTeacherRequest,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Assign a teacher to a class and subject"""
    class_id = body.class_id
    subject_id = body.subject_id
    academic_term_id = body.academic_term_id
    is_class_teacher = body.is_class_teacher
    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    
    if staff.staff_type != StaffType.TEACHING:
        raise HTTPException(status_code=400, detail="Staff is not a teacher")
    
    if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    existing = await session.execute(
        select(TeacherAssignment).where(
            TeacherAssignment.staff_id == staff_id,
            TeacherAssignment.class_id == class_id,
            TeacherAssignment.subject_id == subject_id,
            TeacherAssignment.academic_term_id == academic_term_id
        )
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="Assignment already exists")

    if is_class_teacher:
        await ensure_single_class_teacher(session, class_id, academic_term_id)

    assignment = TeacherAssignment(
        school_id=staff.school_id,
        staff_id=staff_id,
        class_id=class_id,
        subject_id=subject_id,
        academic_term_id=academic_term_id,
        is_class_teacher=is_class_teacher
    )
    session.add(assignment)
    await session.commit()
    
    return {"message": "Teacher assigned successfully", "assignment_id": assignment.id}


@router.patch("/{staff_id}/assignments/{assignment_id}", response_model=dict)
async def update_assignment(
    staff_id: str,
    assignment_id: str,
    data: TeacherAssignmentUpdate,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Update a teacher assignment — replace the teacher and/or toggle the class-teacher flag"""
    result = await session.execute(
        select(TeacherAssignment).where(
            TeacherAssignment.id == assignment_id,
            TeacherAssignment.staff_id == staff_id
        )
    )
    assignment = result.scalar_one_or_none()

    if not assignment:
        raise HTTPException(status_code=404, detail="Assignment not found")

    if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != assignment.school_id:
        raise HTTPException(status_code=403, detail="Access denied")

    update_data = data.model_dump(exclude_unset=True)
    new_staff_id = update_data.get("staff_id")

    if new_staff_id and new_staff_id != assignment.staff_id:
        staff_result = await session.execute(select(Staff).where(Staff.id == new_staff_id))
        new_staff = staff_result.scalar_one_or_none()

        if not new_staff:
            raise HTTPException(status_code=404, detail="Staff not found")
        if new_staff.staff_type != StaffType.TEACHING:
            raise HTTPException(status_code=400, detail="Staff is not a teacher")
        if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != new_staff.school_id:
            raise HTTPException(status_code=403, detail="Access denied")

        dup = await session.execute(
            select(TeacherAssignment).where(
                TeacherAssignment.staff_id == new_staff_id,
                TeacherAssignment.class_id == assignment.class_id,
                TeacherAssignment.subject_id == assignment.subject_id,
                TeacherAssignment.academic_term_id == assignment.academic_term_id,
                TeacherAssignment.id != assignment_id,
            )
        )
        if dup.scalar_one_or_none():
            raise HTTPException(status_code=400, detail="This teacher is already assigned to this subject for this class and term")

    new_is_class_teacher = update_data.get("is_class_teacher")
    if new_is_class_teacher and not assignment.is_class_teacher:
        await ensure_single_class_teacher(
            session, assignment.class_id, assignment.academic_term_id, exclude_assignment_id=assignment_id
        )

    for field, value in update_data.items():
        setattr(assignment, field, value)

    session.add(assignment)
    await session.commit()

    return {"message": "Assignment updated successfully"}


@router.delete("/{staff_id}/assignments/{assignment_id}", response_model=dict)
async def remove_assignment(
    staff_id: str,
    assignment_id: str,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Remove a teacher assignment"""
    result = await session.execute(
        select(TeacherAssignment).where(
            TeacherAssignment.id == assignment_id,
            TeacherAssignment.staff_id == staff_id
        )
    )
    assignment = result.scalar_one_or_none()

    if not assignment:
        raise HTTPException(status_code=404, detail="Assignment not found")

    if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != assignment.school_id:
        raise HTTPException(status_code=403, detail="Access denied")

    await session.delete(assignment)
    await session.commit()

    return {"message": "Assignment removed"}


@router.post("/{staff_id}/portal-credentials", response_model=dict)
async def regenerate_staff_portal_credentials(
    staff_id: str,
    current_user: User = Depends(require_roles(UserRole.SUPER_ADMIN, UserRole.SCHOOL_ADMIN)),
    session: AsyncSession = Depends(get_session)
):
    """Regenerate portal credentials for a staff member"""
    result = await session.execute(select(Staff).where(Staff.id == staff_id))
    staff = result.scalar_one_or_none()
    
    if not staff:
        raise HTTPException(status_code=404, detail="Staff not found")
    
    if current_user.role == UserRole.SCHOOL_ADMIN and current_user.school_id != staff.school_id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    # Delete existing user if exists (with OTP cleanup)
    if staff.user_id:
        await _delete_user_with_otp_cleanup(staff.user_id, session)
    
    # Create new user
    portal_user, portal_password = await _create_portal_user(
        first_name=staff.first_name,
        last_name=staff.last_name,
        school_id=staff.school_id,
        role=staff.role or UserRole.TEACHER,
        session=session
    )
    
    staff.user_id = portal_user.id
    session.add(staff)
    await session.commit()
    
    return {
        "portal_account": {
            "email": portal_user.email,
            "password": portal_password
        }
    }
