"""Teacher Portal - Assignments Management Router

Endpoints for teachers to:
- Create and manage assignments
- View student submissions
- Grade submissions
- Track assignment status
"""

from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File, Form
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, func
from typing import Optional, List
from datetime import datetime
from pathlib import Path
import uuid
import json

from models.staff import TeacherAssignment, Staff
from models.student import Student
from models.classroom import Class, Subject
from models.school import AcademicTerm
from models.assignment import (
    Assignment, AssignmentStatus, AssignmentQuestion, Submission, SubmissionStatus,
    CourseModule, CourseModuleCreate, CourseModuleUpdate,
    CourseModuleItem, CourseModuleItemCreate,
)
from fastapi.encoders import jsonable_encoder
from database import get_session
from auth import get_current_user, require_roles
from models.user import User, UserRole
from services.plan_gating import require_plan_feature
from services.assignment_grade_bridge import sync_submission_to_grade

COURSE_VIDEO_UPLOAD_DIR = Path("uploads/course-videos")
COURSE_VIDEO_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
ALLOWED_VIDEO_CONTENT_TYPES = {"video/mp4", "video/webm", "video/quicktime", "video/x-msvideo"}
MAX_VIDEO_FILE_SIZE_BYTES = 200 * 1024 * 1024  # 200 MB — matches routers/library.py's item upload cap


router = APIRouter(
    prefix="/teacher/assignments", tags=["teacher-assignments"],
    dependencies=[Depends(require_plan_feature("homework_module"))],
)


# ============================================================================
# COURSE MODULES - Lightweight LMS (structured modules of video links /
# learning materials)
#
# NOTE: these static "/course-modules..." routes MUST be registered before
# the "/{assignment_id}" family of routes below — FastAPI/Starlette matches
# routes in registration order, and "/course-modules" would otherwise be
# swallowed by the single-segment "/{assignment_id}" path-parameter route.
# ============================================================================

async def _get_teaching_staff(current_user: User, session: AsyncSession) -> Staff:
    staff_result = await session.execute(
        select(Staff).where(Staff.user_id == current_user.id)
    )
    staff = staff_result.scalar_one_or_none()
    if not staff and current_user.school_id:
        staff_result = await session.execute(
            select(Staff).where(
                and_(Staff.email == current_user.email, Staff.school_id == current_user.school_id)
            )
        )
        staff = staff_result.scalar_one_or_none()
    if not staff:
        raise HTTPException(status_code=404, detail="Staff profile not found. Please ensure your portal credentials have been generated by the admin.")
    return staff


@router.get("/course-modules", response_model=List[dict])
async def list_course_modules(
    class_id: Optional[str] = None,
    subject_id: Optional[str] = None,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """List course modules created by the teacher, with their items —
    each item enriched with completion analytics (completed_count /
    total_students / completion_percentage), so a teacher can see e.g.
    "68% of the class watched this" without a separate endpoint. For
    video/material items, "completed" comes from StudentModuleProgress
    (the student's manual checkmark). For quiz/assessment items
    (assignment_id set), "completed" comes from Submission.status != NOT_SUBMITTED
    instead — a quiz's completion can't be self-reported."""
    staff = await _get_teaching_staff(current_user, session)

    query = select(CourseModule).where(
        CourseModule.school_id == current_user.school_id,
        CourseModule.teacher_id == staff.id,
    )
    if class_id:
        query = query.where(CourseModule.class_id == class_id)
    if subject_id:
        query = query.where(CourseModule.subject_id == subject_id)
    query = query.order_by(CourseModule.order_index, CourseModule.created_at)

    result = await session.execute(query)
    modules = result.scalars().all()

    module_ids = [m.id for m in modules]
    items_by_module = {}
    all_items = []
    if module_ids:
        items_result = await session.execute(
            select(CourseModuleItem)
            .where(CourseModuleItem.module_id.in_(module_ids))
            .order_by(CourseModuleItem.order_index, CourseModuleItem.created_at)
        )
        all_items = list(items_result.scalars().all())

    # total_students per class — the denominator for every item's percentage
    class_ids = {m.class_id for m in modules}
    total_students_by_class = {}
    if class_ids:
        from models.student import StudentStatus
        counts_result = await session.execute(
            select(Student.class_id, func.count(Student.id))
            .where(
                Student.school_id == current_user.school_id,
                Student.class_id.in_(class_ids),
                Student.status == StudentStatus.ACTIVE,
            )
            .group_by(Student.class_id)
        )
        total_students_by_class = dict(counts_result.all())

    # completed_count for video/material items, via StudentModuleProgress
    progress_item_ids = [i.id for i in all_items if not i.assignment_id]
    progress_counts = {}
    if progress_item_ids:
        from models.assignment import StudentModuleProgress
        progress_result = await session.execute(
            select(StudentModuleProgress.module_item_id, func.count(func.distinct(StudentModuleProgress.student_id)))
            .where(StudentModuleProgress.module_item_id.in_(progress_item_ids))
            .group_by(StudentModuleProgress.module_item_id)
        )
        progress_counts = dict(progress_result.all())

    # completed_count for quiz/assessment items, via Submission (any status
    # other than NOT_SUBMITTED counts as "engaged with it")
    assignment_ids = [i.assignment_id for i in all_items if i.assignment_id]
    submission_counts = {}
    if assignment_ids:
        submission_result = await session.execute(
            select(Submission.assignment_id, func.count(func.distinct(Submission.student_id)))
            .where(
                Submission.assignment_id.in_(assignment_ids),
                Submission.status != SubmissionStatus.NOT_SUBMITTED,
            )
            .group_by(Submission.assignment_id)
        )
        submission_counts = dict(submission_result.all())

    module_by_id = {m.id: m for m in modules}
    for item in all_items:
        module = module_by_id.get(item.module_id)
        total = total_students_by_class.get(module.class_id, 0) if module else 0
        completed = submission_counts.get(item.assignment_id, 0) if item.assignment_id else progress_counts.get(item.id, 0)
        percentage = round((completed / total) * 100, 1) if total > 0 else 0.0
        items_by_module.setdefault(item.module_id, []).append({
            **jsonable_encoder(item),
            "completed_count": completed,
            "total_students": total,
            "completion_percentage": percentage,
        })

    return [
        {**jsonable_encoder(m), "items": items_by_module.get(m.id, [])}
        for m in modules
    ]


@router.post("/course-modules", response_model=dict)
async def create_course_module(
    data: CourseModuleCreate,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_teaching_staff(current_user, session)

    assignment_result = await session.execute(
        select(TeacherAssignment).where(
            and_(
                TeacherAssignment.school_id == current_user.school_id,
                TeacherAssignment.staff_id == staff.id,
                TeacherAssignment.class_id == data.class_id,
                TeacherAssignment.subject_id == data.subject_id,
            )
        )
    )
    if not assignment_result.scalar_one_or_none():
        raise HTTPException(status_code=403, detail="You are not assigned to teach this class/subject")

    module = CourseModule(**data.dict(), school_id=current_user.school_id, teacher_id=staff.id)
    session.add(module)
    await session.commit()
    await session.refresh(module)
    return {**jsonable_encoder(module), "items": []}


@router.put("/course-modules/{module_id}", response_model=dict)
async def update_course_module(
    module_id: str,
    data: CourseModuleUpdate,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_teaching_staff(current_user, session)
    result = await session.execute(
        select(CourseModule).where(CourseModule.id == module_id, CourseModule.school_id == current_user.school_id)
    )
    module = result.scalar_one_or_none()
    if not module:
        raise HTTPException(status_code=404, detail="Course module not found")
    if module.teacher_id != staff.id:
        raise HTTPException(status_code=403, detail="You can only edit your own course modules")

    for key, value in data.dict(exclude_unset=True).items():
        setattr(module, key, value)
    module.updated_at = datetime.utcnow()
    session.add(module)
    await session.commit()
    await session.refresh(module)
    return jsonable_encoder(module)


@router.delete("/course-modules/{module_id}", response_model=dict)
async def delete_course_module(
    module_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_teaching_staff(current_user, session)
    result = await session.execute(
        select(CourseModule).where(CourseModule.id == module_id, CourseModule.school_id == current_user.school_id)
    )
    module = result.scalar_one_or_none()
    if not module:
        raise HTTPException(status_code=404, detail="Course module not found")
    if module.teacher_id != staff.id:
        raise HTTPException(status_code=403, detail="You can only delete your own course modules")

    await session.delete(module)
    await session.commit()
    return {"success": True, "message": "Course module deleted"}


@router.post("/course-modules/{module_id}/items", response_model=dict)
async def add_course_module_item(
    module_id: str,
    data: CourseModuleItemCreate,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_teaching_staff(current_user, session)
    result = await session.execute(
        select(CourseModule).where(CourseModule.id == module_id, CourseModule.school_id == current_user.school_id)
    )
    module = result.scalar_one_or_none()
    if not module:
        raise HTTPException(status_code=404, detail="Course module not found")
    if module.teacher_id != staff.id:
        raise HTTPException(status_code=403, detail="You can only edit your own course modules")

    if not data.video_url and not data.assignment_id and not data.learning_material_id:
        raise HTTPException(status_code=400, detail="Provide a video link or select an assignment for this item")

    if data.assignment_id:
        assignment_result = await session.execute(
            select(Assignment).where(
                and_(
                    Assignment.id == data.assignment_id,
                    Assignment.school_id == current_user.school_id,
                    Assignment.teacher_id == staff.id,
                )
            )
        )
        if not assignment_result.scalar_one_or_none():
            raise HTTPException(status_code=404, detail="Assignment not found")

    item = CourseModuleItem(
        **data.dict(),
        school_id=current_user.school_id,
        module_id=module_id,
        video_source="link" if data.video_url else None,
    )
    session.add(item)
    await session.commit()
    await session.refresh(item)
    return jsonable_encoder(item)


@router.post("/course-modules/{module_id}/items/upload-video", response_model=dict)
async def upload_course_module_video(
    module_id: str,
    title: str = Form(...),
    file: UploadFile = File(...),
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Upload a video file directly (real hosting, not a link) and attach it
    as a new module item in one step. Saved under uploads/course-videos/ and
    served from this app's own /uploads static mount — no external video
    platform involved. Mirrors routers/library.py::_save_validated_upload's
    validation/storage pattern exactly."""
    staff = await _get_teaching_staff(current_user, session)
    result = await session.execute(
        select(CourseModule).where(CourseModule.id == module_id, CourseModule.school_id == current_user.school_id)
    )
    module = result.scalar_one_or_none()
    if not module:
        raise HTTPException(status_code=404, detail="Course module not found")
    if module.teacher_id != staff.id:
        raise HTTPException(status_code=403, detail="You can only edit your own course modules")

    if file.content_type not in ALLOWED_VIDEO_CONTENT_TYPES:
        raise HTTPException(status_code=400, detail=f"Unsupported video type: {file.content_type}. Allowed: MP4, WebM, MOV, AVI.")

    content = await file.read()
    if len(content) > MAX_VIDEO_FILE_SIZE_BYTES:
        raise HTTPException(status_code=400, detail="Video exceeds the 200 MB limit.")

    filename = f"{uuid.uuid4()}_{Path(file.filename or 'upload').name}"
    target_path = COURSE_VIDEO_UPLOAD_DIR / current_user.school_id / filename
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_bytes(content)
    video_url = f"/uploads/course-videos/{current_user.school_id}/{filename}"

    item = CourseModuleItem(
        title=title,
        video_url=video_url,
        video_source="upload",
        school_id=current_user.school_id,
        module_id=module_id,
    )
    session.add(item)
    await session.commit()
    await session.refresh(item)
    return jsonable_encoder(item)


@router.delete("/course-modules/items/{item_id}", response_model=dict)
async def delete_course_module_item(
    item_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    staff = await _get_teaching_staff(current_user, session)
    result = await session.execute(
        select(CourseModuleItem).where(CourseModuleItem.id == item_id, CourseModuleItem.school_id == current_user.school_id)
    )
    item = result.scalar_one_or_none()
    if not item:
        raise HTTPException(status_code=404, detail="Module item not found")

    module_result = await session.execute(select(CourseModule).where(CourseModule.id == item.module_id))
    module = module_result.scalar_one_or_none()
    if not module or module.teacher_id != staff.id:
        raise HTTPException(status_code=403, detail="You can only edit your own course modules")

    if item.video_source == "upload" and item.video_url:
        try:
            Path(item.video_url.lstrip("/")).unlink(missing_ok=True)
        except OSError:
            pass

    await session.delete(item)
    await session.commit()
    return {"success": True, "message": "Module item deleted"}


@router.post("", response_model=dict)
async def create_assignment(
    assignment_data: dict,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """
    Create a new assignment for a class.
    Teachers can only create assignments for classes they teach.
    
    Body:
    {
        "class_id": int,
        "subject_id": int,
        "title": str,
        "description": str,
        "due_date": "YYYY-MM-DD",
        "total_points": float (optional, default 100),
        "instructions": str (optional),
    }
    """
    try:
        school_id = current_user.school_id
        
        # Get the Staff record for this user
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar()
        
        # Fallback: try to match by email and school
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(
                    and_(
                        Staff.email == current_user.email,
                        Staff.school_id == current_user.school_id
                    )
                )
            )
            staff = staff_result.scalar()
        
        if not staff:
            raise HTTPException(
                status_code=404,
                detail="Staff profile not found. Please ensure your portal credentials have been generated by the admin."
            )
        
        staff_id = staff.id
        
        # Verify teacher is assigned to teach this class/subject
        assignment_result = await session.execute(
            select(TeacherAssignment).where(
                and_(
                    TeacherAssignment.school_id == school_id,
                    TeacherAssignment.staff_id == staff_id,
                    TeacherAssignment.class_id == assignment_data.get("class_id"),
                    TeacherAssignment.subject_id == assignment_data.get("subject_id"),
                )
            )
        )
        assignment = assignment_result.scalar()
        
        if not assignment:
            raise HTTPException(
                status_code=403,
                detail="You are not assigned to teach this class/subject"
            )
        
        # Verify class and subject exist
        class_result = await session.execute(
            select(Class).where(Class.id == assignment_data.get("class_id"))
        )
        class_obj = class_result.scalar()
        
        if not class_obj:
            raise HTTPException(status_code=404, detail="Class not found")
        
        subject_result = await session.execute(
            select(Subject).where(Subject.id == assignment_data.get("subject_id"))
        )
        subject = subject_result.scalar()
        
        if not subject:
            raise HTTPException(status_code=404, detail="Subject not found")
        
        # Resolve and validate the academic term (previously defaulted to a
        # hardcoded "1" with no existence/school/lock check at all).
        requested_term_id = assignment_data.get("academic_term_id")
        if requested_term_id:
            term_result = await session.execute(
                select(AcademicTerm).where(AcademicTerm.id == requested_term_id, AcademicTerm.school_id == school_id)
            )
        else:
            term_result = await session.execute(
                select(AcademicTerm).where(AcademicTerm.school_id == school_id, AcademicTerm.is_current == True)
            )
        term = term_result.scalar_one_or_none()
        if not term:
            raise HTTPException(
                status_code=400,
                detail="academic_term_id does not exist for this school and no current term is set"
            )
        if term.is_locked:
            raise HTTPException(status_code=423, detail="This academic term is locked and no longer accepts new assignments")

        # Create assignment record in database
        assignment_id = str(uuid.uuid4())

        # Parse due_date if it's a string
        due_date = assignment_data.get("due_date")
        if due_date and isinstance(due_date, str):
            from datetime import datetime as dt
            due_date = dt.fromisoformat(due_date.replace('Z', '+00:00')).date()

        # Create rubric/grading settings JSON if provided
        rubric_data = None
        if assignment_data.get("grading_settings"):
            rubric_data = json.dumps(assignment_data.get("grading_settings"))

        assignment = Assignment(
            id=assignment_id,
            school_id=school_id,
            teacher_id=staff_id,
            class_id=assignment_data.get("class_id"),
            subject_id=assignment_data.get("subject_id"),
            academic_term_id=term.id,
            title=assignment_data.get("title"),
            description=assignment_data.get("description", ""),
            assignment_type=assignment_data.get("assignment_type", "classwork"),
            status=AssignmentStatus.DRAFT,
            instructions=assignment_data.get("instructions", ""),
            rubric=rubric_data,
            points_possible=assignment_data.get("points_possible", 100),
            due_date=due_date,
            recorded_by=current_user.id,
            created_at=datetime.utcnow(),
            updated_at=datetime.utcnow(),
            created_date=datetime.utcnow()
        )
        
        session.add(assignment)
        await session.commit()
        
        # Save questions if provided
        if assignment_data.get("questions"):
            for q_data in assignment_data.get("questions"):
                question = AssignmentQuestion(
                    id=str(uuid.uuid4()),
                    school_id=school_id,
                    assignment_id=assignment_id,
                    question_text=q_data.get("question"),
                    question_type=q_data.get("type", "essay"),
                    options=json.dumps(q_data.get("options", [])) if q_data.get("options") else None,
                    correct_answer=q_data.get("answer"),
                    points=1.0,
                    created_at=datetime.utcnow(),
                    updated_at=datetime.utcnow()
                )
                session.add(question)
            await session.commit()
        
        return {
            "message": "Assignment created successfully",
            "assignment_id": assignment_id,
            "title": assignment_data.get("title"),
            "class_id": assignment_data.get("class_id"),
            "subject_id": assignment_data.get("subject_id"),
            "due_date": due_date.isoformat() if due_date else None,
            "created_by": staff_id,
            "created_at": datetime.utcnow().isoformat(),
            "questions_count": len(assignment_data.get("questions", []))
        }
        
    except HTTPException:
        raise
    except Exception as e:
        await session.rollback()
        raise HTTPException(status_code=500, detail=f"Error creating assignment: {str(e)}")


@router.get("/my-assignments", response_model=dict)
async def get_my_assignments(
    class_id: Optional[str] = None,
    subject_id: Optional[str] = None,
    page: int = Query(1, ge=1),
    limit: int = Query(20, ge=1, le=100),
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """
    Get all assignments created by the teacher.
    Optionally filter by class and/or subject.
    """
    try:
        school_id = current_user.school_id
        
        # Get the Staff record for this user
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar()
        
        # Fallback: try to match by email and school
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(
                    and_(
                        Staff.email == current_user.email,
                        Staff.school_id == current_user.school_id
                    )
                )
            )
            staff = staff_result.scalar()
        
        if not staff:
            raise HTTPException(
                status_code=404,
                detail="Staff profile not found."
            )
        
        staff_id = staff.id
        
        # Build query for teacher's assignments
        query = select(Assignment).where(
            and_(
                Assignment.school_id == school_id,
                Assignment.teacher_id == staff_id,
            )
        )
        
        # Apply filters if provided
        if class_id:
            query = query.where(Assignment.class_id == class_id)
        if subject_id:
            query = query.where(Assignment.subject_id == subject_id)
        
        # Get total count
        count_result = await session.execute(
            select(func.count(Assignment.id)).where(
                and_(
                    Assignment.school_id == school_id,
                    Assignment.teacher_id == staff_id,
                )
            )
        )
        total = count_result.scalar() or 0
        
        # Apply pagination
        offset = (page - 1) * limit
        query = query.offset(offset).limit(limit)
        
        # Get assignments
        result = await session.execute(query)
        assignments = result.scalars().all()
        
        # Format response
        assignments_list = []
        for assignment in assignments:
            # Get class and subject names
            class_result = await session.execute(
                select(Class).where(Class.id == assignment.class_id)
            )
            cls = class_result.scalar()
            
            subject_result = await session.execute(
                select(Subject).where(Subject.id == assignment.subject_id)
            )
            subj = subject_result.scalar()
            
            assignments_list.append({
                "assignment_id": assignment.id,
                "id": assignment.id,
                "title": assignment.title,
                "description": assignment.description,
                "class_id": assignment.class_id,
                "class_name": cls.name if cls else "Unknown",
                "subject_id": assignment.subject_id,
                "subject_name": subj.name if subj else "Unknown",
                "assignment_type": assignment.assignment_type,
                "status": assignment.status,
                "due_date": assignment.due_date.isoformat() if assignment.due_date else None,
                "points_possible": assignment.points_possible,
                "total_points": assignment.points_possible,
                "created_at": assignment.created_at.isoformat() if assignment.created_at else None,
            })
        
        total_pages = (total + limit - 1) // limit if total > 0 else 0
        
        return {
            "items": assignments_list,
            "total": total,
            "page": page,
            "limit": limit,
            "pages": total_pages,
            "message": "Assignments retrieved successfully"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error retrieving assignments: {str(e)}")


@router.get("/{assignment_id}", response_model=dict)
async def get_assignment_details(
    assignment_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Get details of a specific assignment — including question text and
    correct_answer, so (unlike a read-only listing) this must be restricted
    to the assignment's own teacher, not just anyone at the same school."""
    try:
        school_id = current_user.school_id

        staff_result = await session.execute(select(Staff).where(Staff.user_id == current_user.id))
        staff = staff_result.scalar()
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(and_(Staff.email == current_user.email, Staff.school_id == current_user.school_id))
            )
            staff = staff_result.scalar()
        if not staff:
            raise HTTPException(status_code=404, detail="Staff profile not found")

        # Get assignment details from database — teacher_id scoped, not just
        # school_id, since this returns question content + correct_answer.
        result = await session.execute(
            select(Assignment).where(
                and_(
                    Assignment.id == assignment_id,
                    Assignment.school_id == school_id,
                    Assignment.teacher_id == staff.id,
                )
            )
        )
        assignment = result.scalar()

        if not assignment:
            raise HTTPException(status_code=404, detail="Assignment not found")
        
        # Get questions
        questions_result = await session.execute(
            select(AssignmentQuestion).where(AssignmentQuestion.assignment_id == assignment_id)
        )
        questions = questions_result.scalars().all()
        
        # Format questions for response
        formatted_questions = []
        for q in questions:
            question_data = {
                "id": q.id,
                "question": q.question_text,
                "type": q.question_type,
                "answer": q.correct_answer,
                "points": q.points,
            }
            
            # Parse options if they exist
            if q.options:
                try:
                    if isinstance(q.options, str):
                        question_data["options"] = json.loads(q.options)
                    else:
                        question_data["options"] = q.options
                except:
                    question_data["options"] = []
            else:
                question_data["options"] = []
            
            formatted_questions.append(question_data)
        
        return {
            "assignment": {
                "id": assignment.id,
                "class_id": assignment.class_id,
                "subject_id": assignment.subject_id,
                "title": assignment.title,
                "description": assignment.description,
                "due_date": assignment.due_date.isoformat() if assignment.due_date else None,
                "total_points": assignment.points_possible,
                "instructions": assignment.instructions,
                "assignment_type": assignment.assignment_type,
                "status": assignment.status,
                "questions_count": len(questions),
                "questions": formatted_questions,
            },
            "message": "Assignment details retrieved successfully"
        }

    except HTTPException:
        # Let a deliberately-raised HTTPException (404s above) propagate
        # as-is — HTTPException is itself an Exception subclass, so the
        # broad except below would otherwise re-wrap a clean 404 into a
        # confusing nested 500.
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error retrieving assignment: {str(e)}")


@router.get("/{assignment_id}/submissions", response_model=dict)
async def get_assignment_submissions(
    assignment_id: str,
    status: Optional[str] = None,
    page: int = Query(1, ge=1),
    limit: int = Query(50, ge=1, le=100),
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """
    Get all submissions for an assignment.
    Optionally filter by submission status (SUBMITTED, GRADED, MISSING, LATE).
    """
    try:
        school_id = current_user.school_id
        
        # Get the Staff record for this user
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar()
        
        # Fallback: try to match by email and school
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(
                    and_(
                        Staff.email == current_user.email,
                        Staff.school_id == current_user.school_id
                    )
                )
            )
            staff = staff_result.scalar()
        
        if not staff:
            raise HTTPException(
                status_code=404,
                detail="Staff profile not found"
            )
        
        # Verify assignment exists and belongs to this teacher
        assignment_result = await session.execute(
            select(Assignment).where(
                Assignment.id == assignment_id,
                Assignment.school_id == school_id,
                Assignment.teacher_id == staff.id
            )
        )
        assignment = assignment_result.scalar_one_or_none()
        
        if not assignment:
            raise HTTPException(status_code=404, detail="Assignment not found")
        
        # Get class to find all students
        class_result = await session.execute(
            select(Class).where(Class.id == assignment.class_id)
        )
        cls = class_result.scalar_one_or_none()
        
        if not cls:
            raise HTTPException(status_code=404, detail="Class not found")
        
        # Get all students in this class
        students_result = await session.execute(
            select(Student).where(Student.class_id == assignment.class_id)
        )
        all_students = students_result.scalars().all()
        
        # Normalize the status filter if provided.
        if status:
            status = status.lower().strip()
            valid_statuses = [s.value for s in SubmissionStatus]
            if status not in valid_statuses:
                raise HTTPException(status_code=400, detail=f"Invalid status filter: {status}")
            status = SubmissionStatus(status)

        # Get submissions for this assignment
        query = select(Submission).where(
            Submission.assignment_id == assignment_id,
            Submission.school_id == school_id
        )
        
        # Filter by status if provided
        if status:
            query = query.where(Submission.status == status)
        
        # Get total count for pagination
        count_query = select(func.count(Submission.id)).where(
            Submission.assignment_id == assignment_id,
            Submission.school_id == school_id
        )
        if status:
            count_query = count_query.where(Submission.status == status)
        
        total_result = await session.execute(count_query)
        total = total_result.scalar() or 0
        
        # Apply pagination
        offset = (page - 1) * limit
        query = query.order_by(Submission.submission_date.desc()).offset(offset).limit(limit)
        
        submissions_result = await session.execute(query)
        submissions = submissions_result.scalars().all()
        
        # Format submissions with student info
        submissions_list = []
        submitted_student_ids = set()
        
        for submission in submissions:
            # Get student info
            student_result = await session.execute(
                select(Student).where(Student.id == submission.student_id)
            )
            student = student_result.scalar_one_or_none()
            
            if student:
                submitted_student_ids.add(student.id)
                status_value = None
                if submission is not None and submission.status is not None:
                    status_value = submission.status.value if isinstance(submission.status, SubmissionStatus) else str(submission.status).lower()
                submissions_list.append({
                    "id": submission.id,
                    "student_id": student.id,
                    "student_name": f"{student.first_name} {student.last_name}",
                    "submission_date": submission.submission_date.isoformat() if submission.submission_date else None,
                    "status": status_value,
                    "score": submission.score,
                    "max_score": submission.max_score,
                    "feedback": submission.feedback,
                    "graded_date": submission.graded_date.isoformat() if submission.graded_date else None,
                    "graded_answers": json.loads(submission.graded_answers) if submission.graded_answers else None,
                    "submission_text": submission.submission_text
                })
        
        # Add missing submissions for students who haven't submitted
        missing_count = 0
        for student in all_students:
            if student.id not in submitted_student_ids:
                missing_count += 1
                # Only add to list if we're on the first page and there's room
                if page == 1 and len(submissions_list) < limit:
                    submissions_list.append({
                        "id": None,
                        "student_id": student.id,
                        "student_name": f"{student.first_name} {student.last_name}",
                        "submission_date": None,
                        "status": SubmissionStatus.NOT_SUBMITTED.value,
                        "score": None,
                        "max_score": assignment.points_possible,
                        "feedback": None,
                        "graded_date": None,
                        "submission_text": None
                    })
        
        # Calculate pages
        total_with_missing = total + missing_count if not status or status == SubmissionStatus.NOT_SUBMITTED.value else total
        pages = (total_with_missing + limit - 1) // limit if total_with_missing > 0 else 1
        
        return {
            "items": submissions_list,
            "total": total_with_missing,
            "page": page,
            "limit": limit,
            "pages": pages,
            "message": f"Retrieved {len(submissions_list)} submissions"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error retrieving submissions: {str(e)}")


@router.post("/{assignment_id}/grade/{submission_id}", response_model=dict)
async def grade_submission(
    assignment_id: str,
    submission_id: str,
    grade_data: dict,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """
    Grade a student submission.
    
    Body:
    {
        "score": float,
        "feedback": str (optional),
        "rubric_scores": dict (optional),
        "question_scores": dict (optional)  # {"question_id": score, ...}
    }
    """
    try:
        school_id = current_user.school_id
        
        # Get the Staff record for this user
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar()
        
        # Fallback: try to match by email and school
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(
                    and_(
                        Staff.email == current_user.email,
                        Staff.school_id == current_user.school_id
                    )
                )
            )
            staff = staff_result.scalar()
        
        if not staff:
            raise HTTPException(
                status_code=404,
                detail="Staff profile not found."
            )
        
        # Get the submission
        submission_result = await session.execute(
            select(Submission).where(
                Submission.id == submission_id,
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id
            )
        )
        submission = submission_result.scalar_one_or_none()
        
        if not submission:
            raise HTTPException(status_code=404, detail="Submission not found")
        
        # Verify teacher owns this assignment
        assignment_result = await session.execute(
            select(Assignment).where(
                Assignment.id == assignment_id,
                Assignment.teacher_id == staff.id,
                Assignment.school_id == school_id
            )
        )
        assignment = assignment_result.scalar_one_or_none()
        
        if not assignment:
            raise HTTPException(status_code=403, detail="You do not have permission to grade this assignment")
        
        # Validate score
        score = grade_data.get("score")
        if score is not None:
            if score < 0 or score > (assignment.points_possible or 100):
                raise HTTPException(
                    status_code=400, 
                    detail=f"Score must be between 0 and {assignment.points_possible or 100}"
                )
        
        # Update the submission
        if score is not None:
            submission.score = float(score)
        if "feedback" in grade_data:
            submission.feedback = grade_data["feedback"]
        if "rubric_scores" in grade_data:
            submission.rubric_scores = json.dumps(grade_data["rubric_scores"])
        if "question_scores" in grade_data:
            submission.graded_answers = json.dumps(grade_data["question_scores"])
        
        submission.status = SubmissionStatus.GRADED
        submission.graded_date = datetime.utcnow()
        submission.graded_by = staff.id

        if score is not None:
            await sync_submission_to_grade(session, submission, assignment, recorded_by=staff.id)

        await session.commit()
        await session.refresh(submission)

        return {
            "message": "Submission graded successfully",
            "submission_id": submission_id,
            "score": submission.score,
            "max_score": submission.max_score,
            "feedback": submission.feedback,
            "graded_by": staff.id,
            "graded_at": submission.graded_date.isoformat(),
        }
        
    except HTTPException:
        raise
    except Exception as e:
        await session.rollback()
        raise HTTPException(status_code=500, detail=f"Error grading submission: {str(e)}")


@router.get("/{assignment_id}/statistics", response_model=dict)
async def get_assignment_statistics(
    assignment_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Get statistics on assignment submissions and grades."""
    try:
        school_id = current_user.school_id

        staff_result = await session.execute(select(Staff).where(Staff.user_id == current_user.id))
        staff = staff_result.scalar()
        if not staff and current_user.school_id:
            staff_result = await session.execute(
                select(Staff).where(and_(Staff.email == current_user.email, Staff.school_id == current_user.school_id))
            )
            staff = staff_result.scalar()
        if not staff:
            raise HTTPException(status_code=404, detail="Staff profile not found")

        # Verify assignment exists and belongs to this teacher — the
        # docstring/comment already claimed this, but the query never
        # actually checked teacher_id, so any teacher at the school could
        # pull another teacher's class average/high/low scores.
        result = await session.execute(
            select(Assignment).where(
                and_(
                    Assignment.id == assignment_id,
                    Assignment.school_id == school_id,
                    Assignment.teacher_id == staff.id,
                )
            )
        )
        assignment = result.scalar()

        if not assignment:
            raise HTTPException(status_code=404, detail="Assignment not found")
        
        # Get students in the class
        students_result = await session.execute(
            select(func.count(Student.id)).where(Student.class_id == assignment.class_id)
        )
        total_students = students_result.scalar() or 0
        
        # Compute submission statistics for this assignment.
        submitted_result = await session.execute(
            select(func.count(Submission.id)).where(
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id,
                Submission.status.in_([
                    SubmissionStatus.SUBMITTED,
                    SubmissionStatus.GRADED,
                    SubmissionStatus.LATE
                ])
            )
        )
        submitted_count = submitted_result.scalar() or 0

        graded_result = await session.execute(
            select(func.count(Submission.id)).where(
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id,
                Submission.status == SubmissionStatus.GRADED
            )
        )
        graded_count = graded_result.scalar() or 0

        late_result = await session.execute(
            select(func.count(Submission.id)).where(
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id,
                Submission.status == SubmissionStatus.LATE
            )
        )
        late_count = late_result.scalar() or 0

        scored_result = await session.execute(
            select(
                func.avg(Submission.score),
                func.max(Submission.score),
                func.min(Submission.score)
            ).where(
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id,
                Submission.score != None
            )
        )
        average_score, highest_score, lowest_score = scored_result.one()

        total_submissions_result = await session.execute(
            select(func.count(Submission.id)).where(
                Submission.assignment_id == assignment_id,
                Submission.school_id == school_id
            )
        )
        total_submissions = total_submissions_result.scalar() or 0
        missing_count = max(0, total_students - total_submissions)

        stats = {
            "total_students": total_students,
            "submitted": submitted_count,
            "graded": graded_count,
            "missing": missing_count,
            "late": late_count,
            "average_score": float(average_score) if average_score is not None else 0,
            "highest_score": float(highest_score) if highest_score is not None else 0,
            "lowest_score": float(lowest_score) if lowest_score is not None else 0,
        }
        
        return {
            "assignment_id": assignment_id,
            "title": assignment.title,
            "statistics": stats,
            "message": "Assignment statistics retrieved successfully"
        }

    except HTTPException:
        # Same reasoning as get_assignment_details — don't let the broad
        # except below re-wrap a deliberate 404 into a confusing 500.
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error retrieving statistics: {str(e)}")


@router.put("/{assignment_id}", response_model=dict)
async def update_assignment(
    assignment_id: str,
    update_data: dict,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Update an assignment (only by the teacher who created it)."""
    try:
        school_id = current_user.school_id
        
        # Get the Staff record for this user
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar()
        
        if not staff:
            staff_result = await session.execute(
                select(Staff).where(
                    and_(
                        Staff.email == current_user.email,
                        Staff.school_id == current_user.school_id
                    )
                )
            )
            staff = staff_result.scalar()
        
        if not staff:
            raise HTTPException(status_code=404, detail="Staff profile not found.")
        
        staff_id = staff.id
        
        print(f"DEBUG UPDATE: assignment_id={assignment_id}, staff_id={staff_id}, school_id={school_id}")
        
        # Get the assignment
        result = await session.execute(
            select(Assignment).where(
                and_(
                    Assignment.id == assignment_id,
                    Assignment.school_id == school_id,
                    Assignment.teacher_id == staff_id
                )
            )
        )
        assignment = result.scalar()
        
        print(f"DEBUG UPDATE: Found assignment: {assignment is not None}")
        
        if not assignment:
            # Try to debug why it wasn't found
            result_all = await session.execute(
                select(Assignment).where(Assignment.id == assignment_id)
            )
            any_assignment = result_all.scalar()
            if any_assignment:
                print(f"DEBUG: Assignment exists but school_id mismatch: expected {school_id}, got {any_assignment.school_id}")
                print(f"DEBUG: Assignment exists but teacher_id mismatch: expected {staff_id}, got {any_assignment.teacher_id}")
            else:
                print(f"DEBUG: Assignment with id {assignment_id} not found at all")
            
            raise HTTPException(status_code=404, detail="Assignment not found or you don't have permission to edit it")

        # The term this assignment is (or would become) attached to must exist
        # for this school and must not be locked — checked before any mutation.
        target_term_id = update_data.get("academic_term_id", assignment.academic_term_id)
        term_result = await session.execute(
            select(AcademicTerm).where(AcademicTerm.id == target_term_id, AcademicTerm.school_id == school_id)
        )
        term = term_result.scalar_one_or_none()
        if not term:
            raise HTTPException(status_code=400, detail="academic_term_id does not exist for this school")
        if term.is_locked:
            raise HTTPException(status_code=423, detail="This academic term is locked and no longer accepts changes")

        # If class_id is being changed, it must be a real class in this school
        # AND the teacher must actually teach that class for this assignment's
        # subject — otherwise a teacher could silently move their assignment
        # to a class (even in another school) they have no TeacherAssignment
        # for, since nothing else in this endpoint re-checks that.
        new_class_id = update_data.get("class_id", assignment.class_id)
        if new_class_id != assignment.class_id:
            class_result = await session.execute(
                select(Class).where(Class.id == new_class_id, Class.school_id == school_id)
            )
            if not class_result.scalar_one_or_none():
                raise HTTPException(status_code=404, detail="class_id does not exist for this school")
            teaches_result = await session.execute(
                select(TeacherAssignment).where(
                    and_(
                        TeacherAssignment.school_id == school_id,
                        TeacherAssignment.staff_id == staff_id,
                        TeacherAssignment.class_id == new_class_id,
                        TeacherAssignment.subject_id == assignment.subject_id,
                    )
                )
            )
            if not teaches_result.scalar_one_or_none():
                raise HTTPException(status_code=403, detail="You are not assigned to teach this class/subject")

        # Update assignment fields
        assignment.title = update_data.get("title", assignment.title)
        assignment.description = update_data.get("description", assignment.description)
        assignment.instructions = update_data.get("instructions", assignment.instructions)
        assignment.assignment_type = update_data.get("assignment_type", assignment.assignment_type)
        assignment.points_possible = update_data.get("points_possible", assignment.points_possible)
        assignment.class_id = new_class_id
        assignment.academic_term_id = term.id
        assignment.updated_at = datetime.utcnow()
        
        # Parse due_date if provided
        if update_data.get("due_date"):
            due_date = update_data.get("due_date")
            if isinstance(due_date, str):
                from datetime import datetime as dt
                due_date = dt.fromisoformat(due_date.replace('Z', '+00:00')).date()
            assignment.due_date = due_date
        
        # Update grading settings if provided
        if update_data.get("grading_settings"):
            assignment.rubric = json.dumps(update_data.get("grading_settings"))
        
        session.add(assignment)
        
        # Update questions if provided
        if "questions" in update_data and update_data.get("questions"):
            # Delete existing questions
            delete_result = await session.execute(
                select(AssignmentQuestion).where(AssignmentQuestion.assignment_id == assignment_id)
            )
            existing_questions = delete_result.scalars().all()
            for q in existing_questions:
                await session.delete(q)
            
            # Add new questions
            for q_data in update_data.get("questions", []):
                question = AssignmentQuestion(
                    id=q_data.get("id") or str(uuid.uuid4()),
                    school_id=school_id,
                    assignment_id=assignment_id,
                    question_text=q_data.get("question", q_data.get("question_text")),
                    question_type=q_data.get("type", q_data.get("question_type", "essay")),
                    options=json.dumps(q_data.get("options", [])) if q_data.get("options") else None,
                    correct_answer=q_data.get("answer", q_data.get("correct_answer")),
                    points=q_data.get("points", 1.0),
                    created_at=datetime.utcnow(),
                    updated_at=datetime.utcnow()
                )
                session.add(question)
        
        await session.commit()
        
        # Refresh to get relationships loaded
        await session.refresh(assignment)
        
        # Return full updated assignment
        return {
            "message": "Assignment updated successfully",
            "assignment": {
                "id": assignment.id,
                "class_id": assignment.class_id,
                "subject_id": assignment.subject_id,
                "teacher_id": assignment.teacher_id,
                "academic_term_id": assignment.academic_term_id,
                "title": assignment.title,
                "description": assignment.description,
                "instructions": assignment.instructions,
                "assignment_type": assignment.assignment_type,
                "due_date": assignment.due_date.isoformat() if assignment.due_date else None,
                "points_possible": assignment.points_possible,
                "status": assignment.status,
                "created_at": assignment.created_at.isoformat() if assignment.created_at else None,
                "updated_at": assignment.updated_at.isoformat() if assignment.updated_at else None,
            }
        }
        
    except HTTPException:
        raise
    except Exception as e:
        await session.rollback()
        raise HTTPException(status_code=500, detail=f"Error updating assignment: {str(e)}")


@router.patch("/{assignment_id}", response_model=dict)
async def patch_assignment(
    assignment_id: str,
    update_data: dict,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Partial update to an assignment (only by the teacher who created it)."""
    # Delegate to PUT endpoint for full update
    return await update_assignment(assignment_id, update_data, current_user, session)


@router.delete("/{assignment_id}", response_model=dict)
async def delete_assignment(
    assignment_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """Delete an assignment (only by the teacher who created it)."""
    try:
        school_id = current_user.school_id
        
        # Get staff record
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar_one_or_none()
        if not staff:
            raise HTTPException(status_code=404, detail="Staff profile not found")
        
        # Get assignment
        assignment_result = await session.execute(
            select(Assignment).where(
                Assignment.id == assignment_id,
                Assignment.school_id == school_id
            )
        )
        assignment = assignment_result.scalar_one_or_none()
        
        if not assignment:
            raise HTTPException(status_code=404, detail="Assignment not found")
        
        # Verify ownership - check if staff is the teacher of this assignment
        if assignment.teacher_id != staff.id:
            raise HTTPException(status_code=403, detail="You can only delete your own assignments")
        
        # Delete associated questions first
        questions_result = await session.execute(
            select(AssignmentQuestion).where(
                AssignmentQuestion.assignment_id == assignment_id
            )
        )
        questions = questions_result.scalars().all()
        for question in questions:
            await session.delete(question)
        
        # Delete the assignment
        await session.delete(assignment)
        await session.commit()
        
        return {
            "message": "Assignment deleted successfully",
            "assignment_id": assignment_id,
        }
        
    except HTTPException:
        raise
    except Exception as e:
        await session.rollback()
        raise HTTPException(status_code=500, detail=f"Error deleting assignment: {str(e)}")


@router.post("/{assignment_id}/publish", response_model=dict)
async def publish_assignment(
    assignment_id: str,
    current_user: User = Depends(require_roles(UserRole.TEACHER)),
    session: AsyncSession = Depends(get_session),
):
    """
    Publish an assignment (moves from DRAFT to PUBLISHED).
    Published assignments become visible to students in their portal.
    """
    try:
        school_id = current_user.school_id
        
        # Get staff record
        staff_result = await session.execute(
            select(Staff).where(Staff.user_id == current_user.id)
        )
        staff = staff_result.scalar_one_or_none()
        if not staff:
            raise HTTPException(status_code=404, detail="Staff profile not found")
        
        # Get assignment
        assignment_result = await session.execute(
            select(Assignment).where(
                Assignment.id == assignment_id,
                Assignment.school_id == school_id
            )
        )
        assignment = assignment_result.scalar_one_or_none()
        
        if not assignment:
            raise HTTPException(status_code=404, detail="Assignment not found")
        
        # Verify ownership - check if staff is the teacher of this assignment
        if assignment.teacher_id != staff.id:
            raise HTTPException(status_code=403, detail="You can only publish your own assignments")
        
        # Check if assignment is in DRAFT status
        if assignment.status != AssignmentStatus.DRAFT:
            raise HTTPException(
                status_code=400,
                detail=f"Can only publish DRAFT assignments. Current status: {assignment.status}"
            )
        
        # Publish the assignment
        assignment.status = AssignmentStatus.PUBLISHED
        assignment.published_date = datetime.utcnow()
        assignment.updated_at = datetime.utcnow()
        
        session.add(assignment)
        await session.commit()
        
        return {
            "message": "Assignment published successfully! Students can now see it.",
            "assignment_id": assignment_id,
            "status": assignment.status,
            "published_date": assignment.published_date.isoformat() if assignment.published_date else None,
        }
        
    except HTTPException:
        raise
    except Exception as e:
        await session.rollback()
        raise HTTPException(status_code=500, detail=f"Error publishing assignment: {str(e)}")
